// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwHzLSXlGFv_WgQGAvuqPzxX38XG79HLA',
    appId: '1:886837928742:web:1a9a5b0eb0afd770c917e7',
    messagingSenderId: '886837928742',
    projectId: 'ulearning-238b0',
    authDomain: 'ulearning-238b0.firebaseapp.com',
    storageBucket: 'ulearning-238b0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1kiC12XdaBT8sHBRn21FbMAirXiIT8Xs',
    appId: '1:886837928742:android:f43862d18d26a40ec917e7',
    messagingSenderId: '886837928742',
    projectId: 'ulearning-238b0',
    storageBucket: 'ulearning-238b0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByGAKpypjm2iGJUSozZgbp-OlYkeI_STI',
    appId: '1:886837928742:ios:b07103a7372d6223c917e7',
    messagingSenderId: '886837928742',
    projectId: 'ulearning-238b0',
    storageBucket: 'ulearning-238b0.appspot.com',
    iosBundleId: 'com.naserebedo.ulearningFlutterBloc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByGAKpypjm2iGJUSozZgbp-OlYkeI_STI',
    appId: '1:886837928742:ios:f12965e9c0279c35c917e7',
    messagingSenderId: '886837928742',
    projectId: 'ulearning-238b0',
    storageBucket: 'ulearning-238b0.appspot.com',
    iosBundleId: 'com.naserebedo.ulearningFlutterBloc.RunnerTests',
  );
}
